---
settings:
  name: NetApp virtualization solutions
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: true
  pdf:
    gen-type: named-only
    zip-level: 1
    zip-filename: netapp-solutions-virtualization.zip
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Soluciones de virtualización
    url: "/index.html"
  - title: Qué hay de nuevo
    url: "/whats-new.html"
  - section: virtualization
  - section: vmware
  - section: hyperv
  - section: osv
  - section: proxmox
  - section: kvm
  - section: migration
  - section: opennebula
  - title: Vídeos
    url: "/videos/index.html"
    entries:
    - title: Virtualización de OpenShift
      url: "/videos/openshift-videos.html"
    - title: Virtualización de VMware
      url: "/videos/vmware-videos.html"
    - title: Virtualización multicloud híbrida
      url: "/videos/hybrid-cloud-videos.html"
  - title: Blogs
    url: "/blogs.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: NetApp solutions
  repo: netapp-solutions-family
