---
sidebar: sidebar 
permalink: proxmox/proxmox-ontap.html 
keywords: netapp, proxmox, proxmox ve, all-flash, nfs, iscsi, ontap, storage, aff 
summary: 'Aprovisione almacenamiento ONTAP para el entorno virtual Proxmox (VE) mediante protocolos NAS (NFS, SMB) y protocolos SAN (FC, iSCSI, NVMe). Seleccione el procedimiento específico del protocolo apropiado para configurar el almacenamiento compartido para su clúster Proxmox VE.' 
---
= Obtenga información sobre los protocolos de almacenamiento para Proxmox VE con NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Aprovisione almacenamiento ONTAP para el entorno virtual Proxmox (VE) mediante protocolos NAS (NFS, SMB) y protocolos SAN (FC, iSCSI, NVMe). Seleccione el procedimiento específico del protocolo apropiado para configurar el almacenamiento compartido para su clúster Proxmox VE.

Asegúrese de que los hosts Proxmox VE tengan FC, Ethernet u otras interfaces compatibles conectadas a conmutadores con comunicación a interfaces lógicas ONTAP . Compruebe siempre el https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"] para configuraciones compatibles. Los escenarios de ejemplo se crean asumiendo que hay dos tarjetas de interfaz de red de alta velocidad disponibles en cada host Proxmox VE que están conectadas entre sí para crear interfaces vinculadas para tolerancia a fallas y rendimiento. Se utilizan las mismas conexiones de enlace ascendente para todo el tráfico de red, incluida la administración del host, el tráfico de máquinas virtuales/contenedores y el acceso al almacenamiento. Cuando haya más interfaces de red disponibles, considere separar el tráfico de almacenamiento de otros tipos de tráfico.

Para obtener información sobre la arquitectura de almacenamiento de ONTAP y los tipos de almacenamiento admitidos, consulte link:proxmox-ontap-architecture.html["Obtenga más información sobre la arquitectura de almacenamiento ONTAP para Proxmox VE"] y link:proxmox-storage-types.html["Obtenga información sobre los tipos de almacenamiento compatibles con Proxmox VE"].


NOTE: Al utilizar LVM con protocolos SAN (FC, iSCSI, NVMe-oF), el grupo de volúmenes puede contener varios LUN o espacios de nombres NVMe. En ese caso, todos los LUN o espacios de nombres deben ser parte del mismo grupo de consistencia para garantizar la integridad de los datos. No admitimos grupos de volúmenes que abarquen varias SVM de ONTAP . Cada grupo de volúmenes debe crearse a partir de LUN o espacios de nombres de la misma SVM.



== Elija un protocolo de almacenamiento

Seleccione el protocolo que coincida con su entorno y requisitos:

* link:proxmox-ontap-smb.html["Configurar el almacenamiento SMB/CIFS"] - Configure recursos compartidos de archivos SMB/CIFS para Proxmox VE con soporte multicanal para tolerancia a fallas y rendimiento mejorado en múltiples conexiones de red.
* link:proxmox-ontap-nfs.html["Configurar el almacenamiento NFS"] - Configure el almacenamiento NFS para Proxmox VE con nConnect o troncalización de sesión para lograr tolerancia a fallas y mejoras de rendimiento mediante múltiples conexiones de red.
* link:proxmox-ontap-fc.html["Configurar LVM con FC"] - Configure el Administrador de volúmenes lógicos (LVM) con Fibre Channel para obtener acceso al almacenamiento en bloque de alto rendimiento y baja latencia en los hosts de Proxmox VE.
* link:proxmox-ontap-iscsi.html["Configurar LVM con iSCSI"] - Configurar el Administrador de volúmenes lógicos (LVM) con iSCSI para el acceso al almacenamiento en bloque a través de redes Ethernet estándar con soporte de múltiples rutas.
* link:proxmox-ontap-nvme-fc.html["Configurar LVM con NVMe/FC"] - Configure el Administrador de volúmenes lógicos (LVM) con NVMe sobre canal de fibra para un almacenamiento en bloque de alto rendimiento utilizando el protocolo NVMe moderno.
* link:proxmox-ontap-nvme-tcp.html["Configurar LVM con NVMe/TCP"] - Configure el Administrador de volúmenes lógicos (LVM) con NVMe sobre TCP para almacenamiento en bloque de alto rendimiento a través de redes Ethernet estándar utilizando el protocolo NVMe moderno.

