---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= Utilice un almacén de datos VMFS basado en FC en ONTAP como almacenamiento principal para el dominio de administración de VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En este caso de uso describimos el procedimiento para crear un almacén de datos VMFS basado en FC en ONTAP como almacenamiento principal para el dominio de gestión de VMware Cloud Foundation (VCF). Este procedimiento resume los componentes necesarios, las configuraciones y los pasos de implementación.



[[introduction]]
== Introducción

Cuando sea pertinente, nos remitiremos a la documentación externa para los pasos que deben seguirse en vCenter, y mencionaremos aquellos pasos que sean específicos de la parte relativa a la configuración del almacenamiento.

Para obtener información sobre cómo convertir un almacén de datos VMFS existente (incluidos iSCSI y NVMe-oF) en un entorno de vSphere con ONTAP, consulta link:vmw-vcf-mgmt-vmfs.html["Convertir el entorno vSphere (datastore VMFS) al dominio de gestión de VCF"].


NOTE: La versión 5.2 de VCF introdujo la capacidad de convertir un entorno existente de vSphere 8 en un dominio de gestión de VCF o importarlo como dominios de carga de trabajo VCF VI. Antes de esta versión, VMware vSAN era la única opción para el almacenamiento principal del dominio de gestión de VCF. Es mejor implementar las máquinas virtuales de controlador NSX en un datastore VMFS basado en FC o usar un switch de red dual para evitar un punto único de fallo. Si esas opciones no están disponibles, considera usar vSAN para alojar esas máquinas virtuales.


NOTE: Esta solución es aplicable a las plataformas ONTAP compatibles con almacenamiento FC, incluidos NetApp ASA, AFF y FAS.



[[prerequisites]]
== Prerrequisitos

En este escenario se utilizan los siguientes componentes y configuraciones:

* Sistema de almacenamiento NetApp con una máquina virtual de almacenamiento (SVM) configurada para permitir tráfico FC.
* Se han creado interfaces lógicas (LIF) en la estructura FC que transportará el tráfico FC y está asociada con la SVM.
* La zonificación se ha configurado para utilizar una única zonificación de iniciador-destino en conmutadores FC para HBA de host y destinos de almacenamiento.
* Crea un almacén de datos VMFS (con LUN FC) en uno de los hosts de vSphere del clúster.


Para obtener información sobre la configuración de los sistemas de almacenamiento ONTAP , consultelink:https://docs.netapp.com/us-en/ontap["Documentación de ONTAP 9"] centro.

Para obtener información sobre cómo configurar VCF, consulta link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentación de VMware Cloud Foundation"].



[[deployment-steps]]
== Pasos de implementación



[[management-domain-default-cluster]]
=== Dominio de administración - Clúster predeterminado

La herramienta VCF Installer es compatible con VMFS en almacenes de datos FC, NFS v3 y vSAN para el dominio de gestión. Los siguientes pasos describen el procedimiento para implementar un dominio de gestión con un almacén de datos VMFS basado en FC en ONTAP como almacenamiento principal.

Para obtener más información sobre cómo usar un entorno existente de vSphere, consulta link:vmw-vcf-mgmt-vmfs.html["Convertir el entorno vSphere (datastore VMFS) al dominio de gestión de VCF"].



[[management-domain-additional-cluster]]
=== Dominio de administración - Clúster adicional

Para ampliar el dominio de gestión con un clúster adicional, consulta https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["Agrega un clúster SDDC a un dominio VCF"].

A grandes rasgos, los pasos para añadir un clúster adicional al dominio de gestión son los siguientes: * asegúrate de que los hosts estén puestos en servicio y de que los grupos de red estén configurados en vCenter. * El LUN está aprovisionado en el sistema de almacenamiento ONTAP y presentado a los hosts del clúster adicional. * Crea un nuevo clúster SDDC en el dominio de gestión en vCenter y sigue las instrucciones del asistente para añadir el clúster adicional al dominio de gestión.



[[reference-video]]
== Vídeo de referencia

.Datastore principal con FC
video::9c51101c-292b-41ef-8dd5-b4cf0131dd62[panopto,width=360]


[[additional-information]]
== Información adicional

Para obtener información sobre la configuración de los sistemas de almacenamiento ONTAP , consultelink:https://docs.netapp.com/us-en/ontap["Documentación de ONTAP 9"] centro.

Para obtener información sobre cómo configurar VCF, consulta link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentación de VMware Cloud Foundation"].
