---
sidebar: sidebar 
permalink: vmware/vmw-vcf-protect-vmsc.html 
keywords: vmware, vcf, protect, vmsc, vsphere, metro, storage, cluster 
summary:  
---
= Obtenga información sobre la integración de la alta disponibilidad de ONTAP con VMware vSphere Metro Storage Cluster (vMSC)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Descubre las soluciones de NetApp que puedes utilizar para integrar la alta disponibilidad de NetApp ONTAP con VMware vSphere Metro Storage Cluster (vMSC). Esto proporciona soluciones sólidas para la gestión y los dominios de cargas de trabajo de VMware Cloud Foundation (VCF).

Esta combinación garantiza la disponibilidad continua de los datos, una conmutación por error fluida y la recuperación ante desastres en emplazamientos geográficamente dispersos, mejorando la resiliencia y la continuidad operativa de las cargas de trabajo críticas. SnapMirror active sync (SAN y NAS) permite que los servicios empresariales sigan funcionando incluso en caso de un fallo del sitio, permitiendo que las aplicaciones realicen la conmutación por error de forma transparente utilizando una copia secundaria. No se requiere ninguna intervención manual ni scripts personalizados para activar una conmutación por error con SnapMirror active sync (SAN y NAS). Se utiliza un mediador ONTAP para supervisar el estado del sitio primario y realizar automáticamente la conmutación por error al sitio secundario en caso de desastre. El mediador ONTAP se implementa en un servidor o máquina virtual independiente que no forma parte de ninguno de los dos sitios, garantizando la disponibilidad del quórum para evitar situaciones de split brain.

Consulte las siguientes soluciones para obtener más detalles.

* link:vmw-vcf-vmsc-mgmt-smas.html["Stretch Cluster para el dominio de gestión usando sincronización activa de SnapMirror (SAN y NAS)"]
* link:vmw-vcf-vmsc-mgmt-mcc.html["Clúster extensible para el dominio de administración mediante MetroCluster"]
* link:vmw-vcf-vmsc-viwld-smas.html["Stretch Cluster para Workload Domain usando la sincronización activa SnapMirror (SAN y NAS)"]
* link:vmw-vcf-vmsc-viwld-mcc.html["Stretch Cluster para un dominio de carga de trabajo usando MetroCluster"]

