---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-nfs.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, nfs 
summary:  
---
= Utilice un almacén de datos NFS en ONTAP como almacenamiento principal para el dominio de administración de VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En este caso de uso describimos el procedimiento para crear un almacén de datos NFS en ONTAP como almacenamiento principal para el dominio de gestión de VMware Cloud Foundation (VCF). Este procedimiento resume los componentes necesarios, los pasos de configuración y el proceso de implementación.



[[introduction]]
== Introducción

Cuando sea pertinente, nos remitiremos a la documentación externa para los pasos que deben seguirse en vCenter, y mencionaremos aquellos pasos que sean específicos de la parte relativa a la configuración del almacenamiento.

Si necesitas usar un almacén de datos NFS 4.1 como almacenamiento principal o si vas a convertir un entorno existente basado en NFS con vSphere y ONTAP, consulta link:vmw-vcf-mgmt-nfs.html["Convertir el entorno vSphere (almacén de datos NFS) al dominio de gestión de VCF"].


NOTE: La versión 5.2 de VCF introdujo la capacidad de convertir un entorno existente de vSphere 8 en un dominio de gestión de VCF o importarlo como dominios de carga de trabajo VCF VI. Antes de esta versión, VMware vSAN era la única opción para el almacenamiento principal del dominio de gestión de VCF. Es mejor implementar las máquinas virtuales de controlador NSX en un datastore VMFS basado en FC o usar un switch de red dual para evitar un punto único de fallo. Si esas opciones no están disponibles, considera usar vSAN para alojar esas máquinas virtuales.


NOTE: Esta solución es aplicable a las plataformas ONTAP compatibles con almacenamiento NFS, entre las que se incluyen NetApp AFF, AFX y FAS.



[[prerequisites]]
== Prerrequisitos

En este escenario se utilizan los siguientes componentes y configuraciones:

* Sistema de almacenamiento NetApp con una máquina virtual de almacenamiento (SVM) configurada para permitir el tráfico NFS.
* Se ha creado una interfaz lógica (LIF) en la red IP que transportará el tráfico NFS y está asociada con la SVM.
* Un clúster de vSphere con al menos 2 hosts de vSphere.
* Almacén de datos NFS montado en uno de los hosts de vSphere con el mismo servidor NFS y la misma ruta de exportación que se usarán para el dominio de gestión.



NOTE: Al implementar un dominio VCF, VCF comprueba la conectividad con el servidor NFS. Esto se lleva a cabo mediante el adaptador de gestión de los hosts vSphere antes de que se añada cualquier adaptador vmkernel adicional con la dirección IP del NFS. Por lo tanto, es necesario asegurarse de que 1) la red de gestión sea enrutable hacia el servidor NFS, o 2) se haya añadido un LIF para la red de gestión al SVM que aloja el volumen del almacén de datos NFS, para garantizar que la validación pueda continuar.

* Asegúrate de que la herramienta ONTAP NFS VAAI esté instalada en uno de los hosts de vSphere que se pueda seleccionar como plantilla para la imagen del clúster.
* Implementa la herramienta VCF Installer.


Para obtener información sobre la configuración de los sistemas de almacenamiento ONTAP , consultelink:https://docs.netapp.com/us-en/ontap["Documentación de ONTAP 9"] centro.

Para obtener información sobre cómo configurar VCF, consulta link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentación de VMware Cloud Foundation"].



[[deployment-steps]]
== Pasos de implementación



[[management-domain-default-cluster]]
=== Dominio de administración - Clúster predeterminado

La herramienta VCF Installer es compatible con VMFS en almacenes de datos FC, NFS v3 y vSAN para el dominio de gestión. Los siguientes pasos describen el procedimiento para implementar un dominio de gestión con un almacén de datos basado en NFSv3 en ONTAP como almacenamiento principal.


NOTE: Valida o ajusta el valor de nConnect para el almacén de datos NFS después de la implementación.

Para obtener más información sobre cómo utilizar un entorno existente de vSphere, consulta link:vmw-vcf-mgmt-nfs.html["Convertir el entorno vSphere (almacén de datos NFS) al dominio de gestión de VCF"].



[[management-domain-additional-cluster]]
=== Dominio de administración - Clúster adicional

Para ampliar el dominio de gestión con un clúster adicional, consulta https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["Agrega un clúster SDDC a un dominio VCF"].

A grandes rasgos, los pasos para añadir un clúster adicional al dominio de gestión son los siguientes: * Asegúrate de que los hosts estén puestos en servicio y de que los grupos de red estén configurados en vCenter. * El volumen de datastore NFS está aprovisionado en el sistema de almacenamiento ONTAP y exportado a los hosts del clúster adicional. * Crea un nuevo SDDC Cluster en el dominio de gestión en vCenter y sigue el asistente para añadir el clúster adicional al dominio de gestión.



[[additional-information]]
== Información adicional

Para obtener información sobre la configuración de los sistemas de almacenamiento ONTAP , consultelink:https://docs.netapp.com/us-en/ontap["Documentación de ONTAP 9"] centro.

Para obtener información sobre cómo configurar VCF, consulta link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentación de VMware Cloud Foundation"].
