---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-mgmt-supp-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= VMFS en FC como almacenamiento complementario para los dominios de carga de trabajo y de gestión de VCF usando ONTAP tools for VMware
:allow-uri-read: 




[[vmfs-on-fc-as-supplemental-storage-for-vcf-workload-and-management-domains-using-ontap-tools-for-vmware]]
== VMFS en FC como almacenamiento complementario para los dominios de carga de trabajo y de gestión de VCF usando ONTAP tools for VMware

[role="lead"]
En este escenario, demostraremos cómo implementar un almacén de datos VMFS con backend de canal de fibra (FC) para dominios de administración y carga de trabajo utilizando herramientas ONTAP .



[[benefits-of-fibre-channel]]
=== Beneficios del canal de fibra

*Alto rendimiento:* FC proporciona velocidades de transferencia de datos de alta velocidad, lo que lo hace ideal para aplicaciones que requieren acceso rápido y confiable a grandes cantidades de datos.

*Baja latencia:* Latencia muy baja, lo cual es crucial para aplicaciones sensibles al rendimiento, como bases de datos y entornos virtualizados.

*Confiabilidad:* Las redes FC son conocidas por su robustez y confiabilidad, con características como redundancia incorporada y corrección de errores.

*Ancho de banda dedicado:* FC proporciona ancho de banda dedicado para el tráfico de almacenamiento, lo que reduce el riesgo de congestión de la red.

Para obtener más información sobre el uso de Fibre Channel con sistemas de almacenamiento NetApp , consulte https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["Aprovisionamiento de SAN con FC"] .



[[scenario-overview]]
=== Descripción general del escenario

El almacén de datos complementario de VCF se aprovisiona como parte de las operaciones de día 2 usando vCenter. Este escenario cubre los siguientes pasos a alto nivel:

* Implementación de herramientas ONTAP en el dominio de gestión
* Registra los servidores de carga de trabajo vCenter en ONTAP tools
* Definir el backend de almacenamiento en el complemento de herramientas ONTAP para VMware vSphere
* Aprovisionar VMFS en el transporte FC




[[prerequisites]]
=== Prerrequisitos

Este escenario requiere los siguientes componentes y configuraciones:

* Un sistema de almacenamiento ONTAP con puertos FC conectados a conmutadores FC.
* SVM creado con FC lifs.
* vSphere con HBA FC conectados a conmutadores FC.
* La zonificación de iniciador-destino único está configurada en los conmutadores FC.
+

NOTE: Utilice la interfaz lógica SVM FC en la configuración de zona en lugar de puertos FC físicos en los sistemas ONTAP .



NetApp recomienda múltiples rutas para LUN FC.

Para obtener información completa sobre la configuración de Fibre Channel en sistemas de almacenamiento ONTAP , consulte https://docs.netapp.com/us-en/ontap/san-management/index.html["Gestión de almacenamiento SAN"] en la documentación de ONTAP 9.

Para obtener más información sobre el uso de VMFS con sistemas de almacenamiento ONTAP , consulte lalink:vmw-vmfs-deploy.html["Guía de implementación para VMFS"] .



[[deployment-steps-for-management-domain]]
=== Pasos de implementación para el dominio de administración

Para implementar ONTAP Tools y usarlo para crear un almacén de datos VMFS en el dominio de administración de VCF, complete los siguientes pasos:

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html["Implementar herramientas ONTAP en el dominio de administración"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["Definir el backend de almacenamiento mediante la interfaz del cliente vSphere"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-datastore.html["Aprovisionar VMFS en FC"]




[[deployment-steps-for-workload-domain]]
=== Pasos para la implementación del dominio de cargas de trabajo

Para implementar ONTAP Tools y usarlo para crear un almacén de datos VMFS en el dominio de carga de trabajo de VCF, sigue estos pasos:

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html["Registra la carga de trabajo vCenter para activar el complemento vCenter"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["Definir el backend de almacenamiento mediante la interfaz del cliente vSphere"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-datastore.html["Aprovisionar VMFS en FC"]




[[additional-information]]
=== Información adicional

Para obtener información sobre la configuración de los sistemas de almacenamiento ONTAP , consultelink:https://docs.netapp.com/us-en/ontap["Documentación de ONTAP 9"] centro.

Para obtener información sobre la configuración de VCF, consultelink:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["Documentación de VMware Cloud Foundation"] .



[[video-demo-for-this-solution]]
== Demostración en vídeo de esta solución

.Almacén de datos complementario con FC
video::96311abf-aa45-4ce9-984b-b4b001005bab[panopto,width=360]