---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= Utiliza un almacén de datos VMFS basado en FC en ONTAP como almacenamiento principal para un dominio de carga de trabajo de VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En este caso de uso describimos el procedimiento para configurar un almacén de datos VMFS de Fibre Channel (FC) en ONTAP como solución de almacenamiento principal para un dominio de cargas de trabajo de VMware Cloud Foundation (VCF). Este procedimiento resume los componentes necesarios, los pasos de configuración y el proceso de implementación.



[[benefits-of-fibre-channel]]
== Beneficios del canal de fibra

*Alto rendimiento:* FC proporciona velocidades de transferencia de datos de alta velocidad, lo que lo hace ideal para aplicaciones que requieren acceso rápido y confiable a grandes cantidades de datos.

*Baja latencia:* Latencia muy baja, lo cual es crucial para aplicaciones sensibles al rendimiento, como bases de datos y entornos virtualizados.

*Confiabilidad:* Las redes FC son conocidas por su robustez y confiabilidad, con características como redundancia incorporada y corrección de errores.

*Ancho de banda dedicado:* FC proporciona ancho de banda dedicado para el tráfico de almacenamiento, lo que reduce el riesgo de congestión de la red.

Para obtener más información sobre el uso de Fibre Channel con sistemas de almacenamiento NetApp , consulte https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["Aprovisionamiento de SAN con FC"] .



[[scenario-overview]]
== Descripción general del escenario

Este escenario cubre los siguientes pasos de alto nivel:

* Cree una máquina virtual de almacenamiento (SVM) con interfaces lógicas (LIF) para el tráfico FC.
* Recopile información WWPN de los hosts que se implementarán y cree grupos de iniciadores correspondientes en el sistema de almacenamiento ONTAP .
* Cree un volumen FC en el sistema de almacenamiento ONTAP .
* Asigna los grupos iniciadores al volumen de FC creado.
* Utilice la zonificación de iniciador-destino único en los conmutadores FC.  Cree una zona para cada iniciador (zona de iniciador único).
+
** Para cada zona, incluya un destino que sea la interfaz lógica ONTAP FC (WWPN) para las SVM.  Debe haber al menos dos interfaces lógicas por nodo por SVM.  No utilice el WWPN de los puertos físicos.


* Crea un grupo de red para el tráfico de vMotion en vCenter.
* Comisiona hosts en vCenter para usarlos en un Workload Domain.
* Implementa un dominio de carga de trabajo en VCF Ops usando un almacén de datos VMFS sobre FC como almacenamiento principal.



NOTE: Esta solución es aplicable a las plataformas ONTAP compatibles con almacenamiento FC, incluyendo NetApp ASAr2, AFF y FAS.



[[prerequisites]]
== Prerrequisitos

En este escenario se utilizan los siguientes componentes y configuraciones:

* Un sistema de almacenamiento ONTAP AFF, ASA o FAS con puertos FC conectados a conmutadores FC.
* SVM creado con FC lifs.
* vSphere con HBA FC conectados a conmutadores FC.
* La zonificación de iniciador-destino único está configurada en los conmutadores FC.
* Asegúrate de que la política multivía de SVM esté configurada en activo-activo.



NOTE: NetApp recomienda múltiples rutas para LUN FC.



[[deployment-steps]]
== Pasos de implementación



[[vcf-workload-domain-default-cluster]]
=== Dominio de carga de trabajo de VCF - Clúster predeterminado

Una vez que el dominio de gestión esté en funcionamiento, puedes crear el dominio de carga de trabajo de VCF:

* Utilizando la interfaz de usuario de VCF Ops. Los hosts vSphere se han puesto en servicio en vCenter y se ha configurado el grupo de red. Utiliza System Manager o la API de ONTAP para implementar el LUN en los hosts vSphere.
* Importa un entorno existente de vSphere como nuevo dominio de carga de trabajo. Puedes usar ONTAP tools for VMware vSphere, System Manager o la ONTAP API para implementar el datastore VMFS en el clúster vSphere.




[[vcf-workload-domain-additional-cluster]]
=== VCF Workload Domain: clúster adicional

Para ampliar el dominio de carga de trabajo con un clúster adicional, consulta https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["Agrega un clúster SDDC a un dominio VCF"].

A grandes rasgos, los pasos para añadir un clúster adicional al dominio de carga de trabajo son los siguientes: * Asegúrate de que los hosts estén puestos en servicio y de que los grupos de red estén configurados en vCenter. * El LUN está aprovisionado en el sistema de almacenamiento ONTAP y presentado a los hosts del clúster adicional. * Crea un nuevo clúster SDDC en el dominio de carga de trabajo en vCenter y sigue el asistente para añadir el clúster adicional al dominio de carga de trabajo.



[[additional-information]]
== Información adicional

Para obtener información sobre la configuración de los sistemas de almacenamiento ONTAP , consultelink:https://docs.netapp.com/us-en/ontap["Documentación de ONTAP 9"] centro.

Para obtener información sobre cómo configurar VCF, consulta link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentación de VMware Cloud Foundation"].
