---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-migration.html 
keywords: vmware, getting, started, overview, netapp 
summary:  
---
= Obtenga información sobre las máquinas virtuales desde VMware vSphere hasta los almacenes de datos ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Los administradores de VMware vSphere pueden mejorar su infraestructura migrando cargas de trabajo a almacenes de datos de NetApp ONTAP .  ONTAP ofrece instantáneas compatibles con VM, clones que hacen uso eficiente del almacenamiento y operaciones vMotion sin inconvenientes al mismo tiempo que admite la administración basada en políticas de almacenamiento (SPBM).  Ya sea que migre desde vSAN, almacenamiento heredado o implemente implementaciones de nube híbrida, ONTAP proporciona un rendimiento mejorado y operaciones de almacenamiento simplificadas para entornos VMware.

Esta migración permite una integración perfecta, una mejor protección de datos y una mayor flexibilidad en la gestión de entornos virtualizados, lo que garantiza una transición fluida con un tiempo de inactividad mínimo.



== Casos de uso

Hay muchas opciones con la migración en términos de origen y destino cuando se considera migrar a almacenes de datos respaldados por ONTAP .

* Migración de sistemas de almacenamiento de terceros (incluido vSAN) a almacenes de datos ONTAP .
* Migración de máquinas virtuales en el mismo clúster de vSphere
* Migración de máquinas virtuales entre varios clústeres de vSphere
* Migración de máquinas virtuales entre servidores vCenter en el mismo dominio SSO
* Migración de máquinas virtuales entre servidores vCenter en diferentes dominios SSO
* Migración de máquinas virtuales entre ubicaciones de centros de datos
* Migración de sistemas de almacenamiento de terceros (incluido vSAN) a almacenes de datos ONTAP .
* Migración de máquinas virtuales en un entorno de nube híbrida


Para obtener más información sobre la migración de cargas de trabajo de VMware a almacenes de datos respaldados por ONTAP , consultelink:migrate-vms-to-ontap-datastore.html["Migrar máquinas virtuales a almacenes de datos de ONTAP"] .
