---
sidebar: sidebar 
permalink: vmware/vmw-vcf-migrate.html 
keywords: vmware, vcf, migrate, import 
summary:  
---
= Obtenga información sobre cómo convertir un entorno de vSphere con almacenes de datos existentes a VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La conversión de un entorno vSphere con almacenes de datos existentes que se ejecutan en ONTAP en un entorno VMware Cloud Foundation (VCF) implica integrar la infraestructura actual en una arquitectura de nube privada moderna.

Este proceso aprovecha la flexibilidad del almacenamiento ONTAP para lograr un acceso y una gestión de datos sin inconvenientes.  Una vez establecido el dominio de administración de VCF, los administradores pueden importar de manera eficiente entornos vSphere adicionales al ecosistema de VCF.  Esta integración mejora la utilización de recursos, simplifica la gestión de la nube privada y garantiza una transición fluida con una interrupción mínima de las cargas de trabajo existentes.

Consulte las siguientes soluciones para conocer los detalles técnicos de la conversión de una instancia de vCenter.

* link:vmw-vcf-mgmt-nfs.html["Convertir una instancia de vCenter existente en un dominio de administración de VCF (NFS)"]
* link:vmw-vcf-mgmt-fc.html["Convertir una instancia de vCenter (almacén de datos FC) en un dominio de administración de VCF"]

