---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-nfs-requirements.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, nfs, array, ontap tools, otv, sddc, sddc manager, ontap tools, ontap tools 10 
summary: Revisa los requisitos para integrar un clúster de vSphere con almacenes de datos NFS de NetApp ONTAP en un dominio de gestión de VMware Cloud Foundation. 
---
= Requisitos de implementación para converger una instancia del servidor vCenter al dominio de gestión de VCF usando almacenes de datos NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Revisa los requisitos para integrar un clúster de vSphere con almacenes de datos NFS de NetApp ONTAP en un dominio de gestión de VMware Cloud Foundation.

El proceso de convergencia requiere un sistema de almacenamiento AFF o AFX, SVMs y LIFs para el tráfico NFS, VLANs de NFS en los switches, un clúster de vSphere con hosts de vSphere y vCenter, y un segmento de red dedicado para vMotion.



[[infrastructure-requirements]]
== Requisitos de infraestructura

Asegúrese de que los siguientes componentes y configuraciones estén en su lugar.

* NetApp sistema de almacenamiento AFF o AFX con una máquina virtual de almacenamiento (SVM) configurada para permitir el tráfico NFS.
* Interfaz lógica (LIF) creada en la red IP para transportar tráfico NFS y asociada con la SVM.
* Un clúster de vSphere con al menos 2 hosts vSphere y un appliance vCenter ubicado en el clúster.
* Grupo de puertos distribuidos configurado para el tráfico de almacenamiento NFS y vMotion en las VLAN o segmentos de red establecidos para este propósito.
* Herramienta VCF Installer para converger el vCenter al dominio de gestión de VCF.
* Requisitos previos para las herramientas ONTAP .
+
Para obtener información completa sobre los requisitos previos para las herramientas ONTAP , consulte https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/prerequisites.html#system-requirements["Requisitos previos para las ONTAP tools for VMware vSphere"] .

+
Las ONTAP tools for VMware vSphere se pueden instalar en configuraciones HA o no HA.





[[additional-resources]]
== Recursos adicionales

* Para conocer los sistemas de almacenamiento compatibles y otras consideraciones relativas a la convergencia de vSphere a VCF, consulta https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/deployment/converging-your-existing-vsphere-infrastructure-to-a-vcf-or-vvf-platform-/supported-and-not-supported-configurations.html["Configuraciones compatibles y no compatibles para converger a VCF"].
* Para obtener información sobre cómo configurar los sistemas de almacenamiento ONTAP , consulte lalink:https://docs.netapp.com/us-en/ontap["Documentación de ONTAP 9"] .
* Para obtener información sobre cómo configurar VCF, consulta la link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentación de VMware Cloud Foundation 9.1"].




[[whats-next]]
== ¿Que sigue?

Después de haber revisado los requisitos de implementación,link:vmw-vcf-mgmt-nfs-deploy.html["Implementar herramientas ONTAP y aprovisionar el almacén de datos NFS"] .
