---
sidebar: sidebar 
permalink: vmware/vmw-dr-gs.html 
keywords: vmware, getting, started, overview, netapp, bluexp, disaster, recovery, draas 
summary:  
---
= Obtenga información sobre la recuperación ante desastres de máquinas virtuales mediante la BlueXP disaster recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La BlueXP disaster recovery automatiza la replicación y recuperación de máquinas virtuales VMware mediante almacenamiento ONTAP .  Admite la recuperación desde la configuración local a VMware Cloud en AWS con Amazon FSx for NetApp ONTAP u otro entorno VMware local.



== Introducción

Contar con un plan exitoso y una combinación de tecnologías garantiza la protección de datos, aplicaciones y máquinas virtuales críticas.  El desafío con la recuperación ante desastres es determinar el nivel apropiado de protección y los costos asociados.

Las matrices ONTAP ofrecen replicación incorporada para transferir datos de volumen y, por lo tanto, las máquinas virtuales que residen en los LUN del almacén de datos designados, de un sitio a otro. BlueXP DRaaS se integra con vSphere y automatiza todo el flujo de trabajo para lograr una conmutación por error y recuperación sin inconvenientes en caso de desastre.

Para obtener más información sobre BlueXP DRaaS, consultelink:https://docs.netapp.com/us-en/netapp-solutions-cloud/vmware/vmw-hybrid-dr-overview.html["Descripción general de BlueXP DRaaS"^] .



== Consideraciones

Las partes que consumen más tiempo de una conmutación por error de DR en un entorno VMware vSphere son la ejecución de los pasos necesarios para inventariar, registrar, reconfigurar y encender las máquinas virtuales en el sitio de DR. Una solución ideal tiene un RPO bajo (medido en minutos) y un RTO bajo (medido en minutos a horas). Un factor que a menudo se pasa por alto en una solución de DR es la capacidad de probar la solución de DR de manera eficiente en un intervalo periódico.

Para diseñar una solución de recuperación ante desastres, tenga en cuenta los siguientes factores:

* El objetivo de tiempo de recuperación (RTO). El RTO es la rapidez con la que una empresa puede recuperarse de un desastre o, más específicamente, el tiempo que lleva ejecutar el proceso de recuperación para que los servicios empresariales estén disponibles nuevamente.
* El objetivo del punto de recuperación (RPO). El RPO es la antigüedad de los datos recuperados después de que se pusieron a disposición, en relación con el momento en que ocurrió el desastre.
* Escalabilidad y adaptabilidad. Este factor incluye la capacidad de aumentar los recursos de almacenamiento de forma incremental a medida que aumenta la demanda.


Para obtener más información técnica sobre las soluciones disponibles, consulte:

* link:https://docs.netapp.com/us-en/netapp-solutions-cloud/vmware/vmw-hybrid-dr-nfs.html["Recuperación ante desastres con BlueXP DRaaS para almacenes de datos NFS"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-cloud/vmware/vmw-hybrid-dr-vmfs.html["Recuperación ante desastres con BlueXP DRaaS para almacenes de datos VMFS"^]

