---
sidebar: sidebar 
permalink: vmware/vmware-smbc-cvt-smas.html 
keywords: NetApp Solutions, vMSC, Metro Storage Cluster, SnapMirror active sync, Business Continuity, SMBC, ONTAP Tools, AFD, SCV, iSCSI, backup, restore 
summary:  
---
= Convierta la sincronización activa de SM de asimétrica a simétrica activa/activa con VMware vSphere Metro Storage Cluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este artículo detalla cómo convertir la sincronización activa de SnapMirror de asimétrica a simétrica activa/activa con VMware vSphere Metro Storage Cluster (VMSC).



== Descripción general

link:https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/["Sincronización activa de NetApp Snapmirror (sincronización activa de SM)"]es una solución robusta para lograr un Objetivo de tiempo de recuperación (RTO) cero y un Objetivo de punto de recuperación (RPO) cero en un entorno virtualizado.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware_vmsc_overview.html["Clúster de almacenamiento VMware vSphere Metro (vMSC)"]es una solución de clúster extendido en diferentes dominios de falla y permite que las máquinas virtuales (VM) se distribuyan en dos sitios separados geográficamente, lo que proporciona disponibilidad continua incluso si falla un sitio.

La combinación de vMSC con SM Active Sync garantiza la consistencia de los datos y capacidades de conmutación por error inmediata entre dos sitios.  Esta configuración es particularmente crucial para aplicaciones de misión crítica donde cualquier pérdida de datos o tiempo de inactividad es inaceptable.

SM active sync, anteriormente conocido como SnapMirror Business Continuity (SMBC), permite que los servicios comerciales sigan funcionando incluso ante una falla total del sitio, permitiendo que las aplicaciones conmuten por error de forma transparente mediante una copia secundaria.  A partir de ONTAP 9.15.1, SM Active sync admite una capacidad activa/activa simétrica.  La replicación activa/activa simétrica permite operaciones de E/S de lectura y escritura desde ambas copias de un LUN protegido con replicación sincrónica bidireccional, de modo que ambas copias de LUN puedan atender operaciones de E/S localmente.

Este documento le muestra los pasos para convertir una sincronización activa asimétrica activa/activa de SM a una sincronización activa simétrica activa/activa de SM en un entorno de clúster VMware Stretch; en otras palabras, convierte una sincronización activa de SM de una política de conmutación por error automatizada a una política de conmutación por error-dúplex automatizada.  Para conocer los detalles sobre cómo configurar vMSC con SnapMirror Active Sync (SM-as) utilizando el Administrador del sistema y las herramientas ONTAP , consultelink:vmw-vmsc-with-smas.html["Clúster de almacenamiento VMware vSphere Metro con sincronización activa de SnapMirror"] .



== Prerrequisitos

* Sistemas de almacenamiento NetApp : asegúrese de tener dos clústeres de almacenamiento NetApp (origen y destino) con licencias de Snapmirror.
* Conectividad de red: verificar la conectividad de red de baja latencia entre los sistemas de origen y destino.
* Intercambio de tráfico de clústeres y SVM: configure el intercambio de tráfico de clústeres y de máquinas virtuales de almacenamiento (SVM) entre los clústeres de origen y destino.
* Versión de ONTAP : asegúrese de que ambos clústeres estén ejecutando una versión de ONTAP que admita la replicación sincrónica.  Para la sincronización activa de SM, se requiere ONTAP 9.15.1 y versiones posteriores.
* Infraestructura VMware vMSC: un clúster extendido permite que los subsistemas abarquen geografías, presentando un conjunto de recursos de infraestructura base único y común al clúster vSphere en ambos sitios.  Extiende la red y el almacenamiento entre sitios.
* Utilice las herramientas ONTAP 10.2 en adelante para facilitar el uso de NetApp SnapMirror. Para más detalles, consultelink:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/release-notes/ontap-tools-9-ontap-tools-10-feature-comparison.html["ONTAP tools for VMware vSphere 10."]
* Debe existir una relación sincrónica de Snapmirror con RPO cero entre el clúster primario y el secundario.
* Se deben desasignar todos los LUN en el volumen de destino antes de que se pueda crear la relación Snapmirror de RTO cero.
* La sincronización activa de Snapmirror solo admite protocolos SAN (no NFS/CIFS).  Asegúrese de que ningún componente del grupo de consistencia esté montado para el acceso NAS.




== Pasos para convertir de sincronización activa SM asimétrica a simétrica

En el siguiente ejemplo, selectrz1 es el sitio principal y selectrz2 es el sitio secundario.

. Desde el sitio secundario, realice una actualización de SnapMirror en la relación existente.
+
....
selectrz2::> snapmirror update -destination-path site2:/cg/CGsite1_dest
....
. Verifique que la actualización de SnapMirror se haya completado exitosamente.
+
....
selectrz2::> snapmirror show
....
. Pausa cada una de las relaciones sincrónicas de RPO cero.
+
....
 selectrz2::> snapmirror quiesce -destination-path site2:/cg/CGsite1_dest
....
. Eliminar cada una de las relaciones sincrónicas de RPO cero.
+
....
selectrz2::> snapmirror delete -destination-path site2:/cg/CGsite1_dest
....
. Libere la relación de origen SnapMirror pero conserve las instantáneas comunes.
+
....
selectrz1::> snapmirror release -relationship-info-only  true -destination-path svm0.1:/cg/CGsite1_dest                                           ".
....
. Cree una relación sincrónica SnapMirror RTO cero con la política AutomatedFailoverDuplex.
+
....
selectrz2::> snapmirror create -source-path svm0.1:/cg/CGsite1 -destination-path site2:/cg/CGsite1_dest -cg-item-mappings site1lun1:@site1lun1_dest -policy AutomatedFailOverDuplex
....
. Si los hosts existentes son locales del clúster principal, agregue el host al clúster secundario y establezca conectividad con el acceso respectivo a cada clúster.
. En el sitio secundario, elimine los mapas LUN en los igroups asociados con los hosts remotos.
+
....
selectrz2::> lun mapping delete -vserver svm0 -igroup wlkd01 -path  /vol/wkld01/wkld01
....
. En el sitio principal, modifique la configuración del iniciador para los hosts existentes para establecer la ruta proximal para los iniciadores en el clúster local.
+
....
selectrz1::> set -privilege advanced
selectrz1::*> igroup initiator add-proximal-vserver -vserver site1  -initiator iqn.1998-01.com.vmware:vcf-wkld-esx01.sddc.netapp.com:575556728:67 -proximal-vserver site1
....
. Agregue un nuevo igroup y un iniciador para los nuevos hosts y configure la proximidad del host para la afinidad del host con su sitio local.  Habilite la replicación de igroup para replicar la configuración e invertir la localidad del host en el clúster remoto.
+
....
selectrz1::*> igroup modify -vserver site1  -igroup smbc2smas -replication-peer svm0.1
selectrz1::*> igroup initiator add-proximal-vserver -vserver site1 -initiator iqn.1998-01.com.vmware:vcf-wkld-esx01.sddc.netapp.com:575556728:67 -proximal-vserver svm0.1
....
. Descubra las rutas en los hosts y verifique que los hosts tengan una ruta activa/optimizada al LUN de almacenamiento desde el clúster preferido.
. Implemente la aplicación y distribuya las cargas de trabajo de la máquina virtual entre los clústeres.
. Resincronizar el grupo de consistencia.
+
....
selectrz2::> snapmirror resync -destination-path site2:/cg/CGsite1_dest
....
. Vuelva a escanear las rutas de E/S del LUN del host para restaurar todas las rutas a los LUN.

