---
sidebar: sidebar 
permalink: openshift/osv-vm-dp-delete-using-velero.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, Red Hat OpenShift, OpenShift Virtualization, CNV, Container Native Virtualization, Red Hat OpenShift Virtualization, OADP operator, Openshift Data Protection Application operator, velero 
summary: Virtualización de Red Hat OpenShift con NetApp ONTAP 
---
= Eliminar una CR de respaldo o restaurar una CR en Red Hat OpenShift Virtualization usando Velero
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Eliminar recursos de copia de seguridad y restauración de máquinas virtuales en OpenShift Virtualization usando Velero.  Utilice la CLI de OpenShift para eliminar copias de seguridad y conservar los datos de almacenamiento de objetos, o la CLI de Velero para eliminar tanto el recurso personalizado de copia de seguridad (CR) como los datos de almacenamiento asociados.



== Eliminar una copia de seguridad

Puede eliminar un CR de respaldo sin eliminar los datos de almacenamiento de objetos mediante la herramienta CLI de OC.

....
oc delete backup <backup_CR_name> -n <velero_namespace>
....
Si desea eliminar la copia de seguridad CR y eliminar los datos de almacenamiento de objetos asociados, puede hacerlo utilizando la herramienta Velero CLI.

Descargue la CLI como se indica en las instrucciones en ellink:https://velero.io/docs/v1.3.0/basic-install/#install-the-cli["Documentación de Velero"] .

Ejecute el siguiente comando de eliminación usando la CLI de Velero

....
velero backup delete <backup_CR_name> -n <velero_namespace>
....


== Eliminar una restauración

Puede eliminar el CR de restauración mediante la CLI de Velero

....
velero restore delete restore --namespace openshift-adp
....
Puede utilizar el comando oc así como la UI para eliminar la CR de restauración

....
oc delete backup <backup_CR_name> -n <velero_namespace>
....